Connected to spar (Python 3.11.9)

In [1]:
import torch as t
import torch
import numpy as np

In [2]:
# load all of the pearson data
filename = f"artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
with open(filename, 'rb') as data:
    interaction_data = np.load(data)['arr_0']

In [ ]:
def ranked_pairs(matrix: np.ndarray) -> np.ndarray:
    m, _ = matrix.shape
    
    # Step 1: Flatten the matrix (shape: [m*m])
    flattened_matrix = matrix.flatten()
    
    # Step 2: Create row and column indices
    row_indices = np.repeat(np.arange(m), m)
    col_indices = np.tile(np.arange(m), m)
    
    # Step 3: Create the final array with indices and values
    values = flattened_matrix
    result = np.column_stack((row_indices, col_indices, values))
    
    # Step 4: Sort the result array by values
    sorted_result = result[result[:, 2].argsort()[::-1]]
    
    return sorted_result

In [ ]:
def ranked_pairs(matrix: np.ndarray) -> np.ndarray:
    m, _ = matrix.shape
    
    # Step 1: Flatten the matrix (shape: [m*m])
    flattened_matrix = matrix.flatten()
    
    # Step 2: Create row and column indices
    row_indices = np.repeat(np.arange(m), m)
    col_indices = np.tile(np.arange(m), m)
    
    # Step 3: Create the final array with indices and values
    values = flattened_matrix
    result = np.column_stack((row_indices, col_indices, values))
    
    # Step 4: Sort the result array by values
    sorted_result = result[result[:, 2].argsort()[::-1]]
    
    return sorted_result

In [ ]:
num_layers, d_sae, _ = interaction_data.shape
"""
1. run a single row through.
it activates L0f{4, 800, 12000} > 0 and that's it

"""

# TODO(IMPORTANT): figure out why all_corrs[0, 14525, 11914] > 1

"\n1. run a single row through.\nit activates L0f{4, 800, 12000} > 0 and that's it\n\n"

In [ ]:
interaction_data[0, 14525, 11914]

1.0000046

In [ ]:
# Find the indices of these maximum values
# TODO: scale this up, remove truncation
flattened_pairs = interaction_data.reshape(num_layers, -1)[:,:10000000]
max_indices = np.argsort(flattened_pairs, axis=1)[:, ::-1]
# Convert flat indices to corresponding (2nd, 3rd) dimension indices
positions_array = np.array(np.unravel_index(max_indices, interaction_data.shape[1:]))

# print("Max values across the first dimension for each index in the second and third dimensions:\n", max_values)
print("Positions in the 2nd and 3rd dimensions:\n", positions_array)

Positions in the 2nd and 3rd dimensions:
 [[[   17   350   264 ...   271   271     0]
  [   88   122    77 ...   271   271     0]
  [  269   238    15 ...   271   271     0]
  ...
  [  241   258    96 ...   271   271     0]
  [  338    67   185 ...   271   271     0]
  [  141   240   330 ...   271   271     0]]

 [[10971 24235 16226 ...  6182  6181     0]
  [ 2731  4359 16583 ...  6143  6142     0]
  [ 5862  7345  9239 ...  6018  6017     0]
  ...
  [ 6730 19459 12906 ...  5579  5578     0]
  [23147  5574 10190 ...  5566  5565     0]
  [21831  9801 13425 ...  5634  5633     0]]]


In [ ]:
positions_array.shape

(2, 11, 10000000)

In [ ]:
num_layers

11

In [ ]:
# %%

import torch as t
import torch
import numpy as np

In [ ]:
# %%

# load all of the pearson data
filename = f"artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
with open(filename, 'rb') as data:
    interaction_data = np.load(data)['arr_0']

In [ ]:
# %%

num_layers, d_sae, _ = interaction_data.shape
"""
1. run a single row through.
it activates L0f{4, 800, 12000} > 0 and that's it

"""

"\n1. run a single row through.\nit activates L0f{4, 800, 12000} > 0 and that's it\n\n"

In [ ]:
num_layersr

NameError: name 'num_layersr' is not defined

In [ ]:
num_layers

11

In [ ]:
interaction_data.reshape(num_layers, -1)[:,:10000000]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
interaction_data.reshape(num_layers, -1)[:,:10000000].shape

(11, 10000000)

In [ ]:
max_indices = np.argsort(flattened_pairs, axis=1)[:, ::-1]

NameError: name 'flattened_pairs' is not defined

In [ ]:
# %%

# Find the indices of these maximum values
# TODO: scale this up, remove truncation
flattened_pairs = interaction_data.reshape(num_layers, -1)[:,:10000000]
max_indices = np.argsort(flattened_pairs, axis=1)[:, ::-1]
# Convert flat indices to corresponding (2nd, 3rd) dimension indices
positions_array = np.array(np.unravel_index(max_indices, interaction_data.shape[1:]))

# print("Max values across the first dimension for each index in the second and third dimensions:\n", max_values)
print("Positions in the 2nd and 3rd dimensions:\n", positions_array)

Positions in the 2nd and 3rd dimensions:
 [[[   17   350   264 ...   271   271     0]
  [   88   122    77 ...   271   271     0]
  [  269   238    15 ...   271   271     0]
  ...
  [  241   258    96 ...   271   271     0]
  [  338    67   185 ...   271   271     0]
  [  141   240   330 ...   271   271     0]]

 [[10971 24235 16226 ...  6182  6181     0]
  [ 2731  4359 16583 ...  6143  6142     0]
  [ 5862  7345  9239 ...  6018  6017     0]
  ...
  [ 6730 19459 12906 ...  5579  5578     0]
  [23147  5574 10190 ...  5566  5565     0]
  [21831  9801 13425 ...  5634  5633     0]]]


In [ ]:
max_indices

array([[ 428763, 8625835, 6504290, ..., 6666278, 6666277,       0],
       [2165419, 3002631, 1908935, ..., 6666239, 6666238,       0],
       [6616806, 5856433,  377879, ..., 6666114, 6666113,       0],
       ...,
       [5929546, 6360067, 2372202, ..., 6665675, 6665674,       0],
       [8329835, 1652166, 4556750, ..., 6665662, 6665661,       0],
       [3487047, 5908041, 8123505, ..., 6665730, 6665729,       0]])

In [ ]:
np.unravel_index(max_indices, num_layers)

ValueError: index 428763 is out of bounds for array with size 11

In [ ]:
np.unravel_index(max_indices, d_sae)

ValueError: index 428763 is out of bounds for array with size 24576

In [ ]:
 positions_array

array([[[   17,   350,   264, ...,   271,   271,     0],
        [   88,   122,    77, ...,   271,   271,     0],
        [  269,   238,    15, ...,   271,   271,     0],
        ...,
        [  241,   258,    96, ...,   271,   271,     0],
        [  338,    67,   185, ...,   271,   271,     0],
        [  141,   240,   330, ...,   271,   271,     0]],

       [[10971, 24235, 16226, ...,  6182,  6181,     0],
        [ 2731,  4359, 16583, ...,  6143,  6142,     0],
        [ 5862,  7345,  9239, ...,  6018,  6017,     0],
        ...,
        [ 6730, 19459, 12906, ...,  5579,  5578,     0],
        [23147,  5574, 10190, ...,  5566,  5565,     0],
        [21831,  9801, 13425, ...,  5634,  5633,     0]]])

In [ ]:
interaction_data.shape[1:]

(24576, 24576)

In [ ]:
positions_array.shape

(2, 11, 10000000)

In [ ]:
interaction_data

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
interaction_data[positions_array]

MemoryError: Unable to allocate 472. PiB for an array with shape (2, 11, 10000000, 24576, 24576) and data type float32

In [ ]:
interaction_data.shape

(11, 24576, 24576)

In [ ]:
np.unravel_index(max_indices, (num_layers, d_sae, d_sae))

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[ 17, 350, 264, ..., 271, 271,   0],
        [ 88, 122,  77, ..., 271, 271,   0],
        [269, 238,  15, ..., 271, 271,   0],
        ...,
        [241, 258,  96, ..., 271, 271,   0],
        [338,  67, 185, ..., 271, 271,   0],
        [141, 240, 330, ..., 271, 271,   0]]),
 array([[10971, 24235, 16226, ...,  6182,  6181,     0],
        [ 2731,  4359, 16583, ...,  6143,  6142,     0],
        [ 5862,  7345,  9239, ...,  6018,  6017,     0],
        ...,
        [ 6730, 19459, 12906, ...,  5579,  5578,     0],
        [23147,  5574, 10190, ...,  5566,  5565,     0],
        [21831,  9801, 13425, ...,  5634,  5633,     0]]))

In [ ]:
np.unravel_index(max_indices, (num_layers, d_sae, d_sae)).shape

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
ur = np.unravel_index(max_indices, (num_layers, d_sae, d_sae))

In [ ]:
ur[0].shape

(11, 10000000)

In [ ]:
ur[1].shape

(11, 10000000)

In [ ]:
ur[2].shape

(11, 10000000)

In [ ]:
ur[3].shape

IndexError: tuple index out of range

In [ ]:
np.argsort(interaction_data[0,:,:], axis=(1, 2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
interaction_data[0,:,:].reshape(d_sae**2)

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
interaction_data[0,:,:].reshape(d_sae**2).shape

(603979776,)

In [ ]:
np.argsort(interaction_data[0,:,:].reshape(d_sae**2))

KeyboardInterrupt: 

In [ ]:
np.argsort(interaction_data[0,:,:].reshape(d_sae**2))[:10000000]

array([337327719, 337315087, 337315280, ..., 411888098, 411888099,
       411888100])

In [ ]:
np.argsort(interaction_data[0,:,:].reshape(d_sae**2)[:10000000])

array([      0, 6666277, 6666278, ..., 6504290, 8625835,  428763])

In [ ]:
np.argsort(interaction_data[0,:,:].reshape(d_sae**2)[:10000000])[::-1]

array([ 428763, 8625835, 6504290, ..., 6666278, 6666277,       0])

In [ ]:
interaction_data[0][np.argsort(interaction_data[0,:,:].reshape(d_sae**2)[:10000000])[::-1]]

IndexError: index 428763 is out of bounds for axis 0 with size 24576

In [ ]:
interaction_data[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
flattened_first_layer = interaction_data[0,:,:].reshape(d_sae**2)

In [ ]:
flattened_first_layer[np.argsort(flattened_first_layer[:10000000])[::-1]]

array([0.99888825, 0.9988738 , 0.9984707 , ..., 0.        , 0.        ,
       0.        ], dtype=float32)

In [ ]:
flattened_truncated_all_layers = interaction_data.reshape(num_layers, d_sae**2)

In [ ]:
flattened_truncated_all_layers = interaction_data.reshape(num_layers, d_sae**2)[:,:10000000]

In [ ]:
np.argsort(flattened_truncated_all_layers, axis=1)[::-1]

array([[      0, 6665729, 6665730, ..., 8123505, 5908041, 3487047],
       [      0, 6665661, 6665662, ..., 4556750, 1652166, 8329835],
       [      0, 6665674, 6665675, ..., 2372202, 6360067, 5929546],
       ...,
       [      0, 6666113, 6666114, ...,  377879, 5856433, 6616806],
       [      0, 6666238, 6666239, ..., 1908935, 3002631, 2165419],
       [      0, 6666277, 6666278, ..., 6504290, 8625835,  428763]])

In [ ]:
flattened_truncated_all_layers[np.argsort(flattened_truncated_all_layers, axis=1)[::-1]]

MemoryError: Unable to allocate 3.91 PiB for an array with shape (11, 10000000, 10000000) and data type float32

In [ ]:
max_idxes_per_truncated_layer = np.argsort(flattened_truncated_all_layers, axis=1)[::-1]

In [ ]:
max_idxes_per_truncated_layer.shape

(11, 10000000)

In [ ]:
flattened_truncated_all_layers.shape

(11, 10000000)

In [ ]:
flattened_truncated_all_layers[max_idxes_per_truncated_layer]

MemoryError: Unable to allocate 3.91 PiB for an array with shape (11, 10000000, 10000000) and data type float32

In [ ]:
max_idxes_per_truncated_layer

array([[      0, 6665729, 6665730, ..., 8123505, 5908041, 3487047],
       [      0, 6665661, 6665662, ..., 4556750, 1652166, 8329835],
       [      0, 6665674, 6665675, ..., 2372202, 6360067, 5929546],
       ...,
       [      0, 6666113, 6666114, ...,  377879, 5856433, 6616806],
       [      0, 6666238, 6666239, ..., 1908935, 3002631, 2165419],
       [      0, 6666277, 6666278, ..., 6504290, 8625835,  428763]])

In [ ]:
flattened_truncated_all_layers[0][max_idxes_per_truncated_layer[0]]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
flattened_truncated_all_layers[0][max_idxes_per_truncated_layer[0]].shape

(10000000,)

In [ ]:
flattened_truncated_all_layers[1][max_idxes_per_truncated_layer[1]].shape

(10000000,)

In [ ]:
flattened_truncated_all_layers[1][max_idxes_per_truncated_layer[1]]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
flattened_truncated_all_layers[1][max_idxes_per_truncated_layer[1]].count_nonzeros()

AttributeError: 'numpy.ndarray' object has no attribute 'count_nonzeros'

In [ ]:
flattened_truncated_all_layers[1][max_idxes_per_truncated_layer[1]].count_nonzero()

AttributeError: 'numpy.ndarray' object has no attribute 'count_nonzero'

In [ ]:
np.count_nonzero(flattened_truncated_all_layers[1][max_idxes_per_truncated_layer[1]])

2817

In [ ]:
max_idxes_per_truncated_layer

array([[      0, 6665729, 6665730, ..., 8123505, 5908041, 3487047],
       [      0, 6665661, 6665662, ..., 4556750, 1652166, 8329835],
       [      0, 6665674, 6665675, ..., 2372202, 6360067, 5929546],
       ...,
       [      0, 6666113, 6666114, ...,  377879, 5856433, 6616806],
       [      0, 6666238, 6666239, ..., 1908935, 3002631, 2165419],
       [      0, 6666277, 6666278, ..., 6504290, 8625835,  428763]])

In [ ]:
max_idxes_per_truncated_layer = np.argsort(flattened_truncated_all_layers, axis=1)

In [ ]:
max_idxes_per_truncated_layer.shape

(11, 10000000)

In [ ]:
max_idxes_per_truncated_layer = np.argsort(flattened_truncated_all_layers, axis=1)[:, ::-1]

In [ ]:
max_idxes_per_truncated_layer

array([[ 428763, 8625835, 6504290, ..., 6666278, 6666277,       0],
       [2165419, 3002631, 1908935, ..., 6666239, 6666238,       0],
       [6616806, 5856433,  377879, ..., 6666114, 6666113,       0],
       ...,
       [5929546, 6360067, 2372202, ..., 6665675, 6665674,       0],
       [8329835, 1652166, 4556750, ..., 6665662, 6665661,       0],
       [3487047, 5908041, 8123505, ..., 6665730, 6665729,       0]])

In [ ]:
flattened_truncated_all_layers[0][max_idxes_per_truncated_layer[0]]

array([0.99888825, 0.9988738 , 0.9984707 , ..., 0.        , 0.        ,
       0.        ], dtype=float32)

In [ ]:
flattened_truncated_all_layers[max_idxes_per_truncated_layer]

MemoryError: Unable to allocate 3.91 PiB for an array with shape (11, 10000000, 10000000) and data type float32

In [ ]:
flattened_truncated_all_layers

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
row_indices = np.arange(num_layers)[:, np.newaxis]

In [ ]:
row_indices

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
flattened_truncated_all_layers[row_indices, max_idxes_per_truncated_layer]

array([[0.99888825, 0.9988738 , 0.9984707 , ..., 0.        , 0.        ,
        0.        ],
       [0.9996799 , 0.9991207 , 0.9989581 , ..., 0.        , 0.        ,
        0.        ],
       [0.99889725, 0.998624  , 0.9984491 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.99862796, 0.99834114, 0.9977249 , ..., 0.        , 0.        ,
        0.        ],
       [0.9958525 , 0.995499  , 0.9954634 , ..., 0.        , 0.        ,
        0.        ],
       [0.99604064, 0.9946885 , 0.99415433, ..., 0.        , 0.        ,
        0.        ]], dtype=float32)