Connected to spar (Python 3.11.9)

In [2]:
import torch as t
import torch
import numpy as np

In [3]:
# load all of the pearson data
filename = f"artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
with open(filename, 'rb') as data:
    interaction_data = np.load(data)['arr_0']

In [4]:
# for speed. set to None to run on all
num_feature_pairs_per_layer = None
num_layers, d_sae, _ = interaction_data.shape

In [6]:
num_layers

11

In [31]:
flattened_truncated_all_layers = interaction_data.reshape(num_layers, d_sae**2)
if num_feature_pairs_per_layer is not None:
    flattened_truncated_all_layers = flattened_truncated_all_layers[:,:num_feature_pairs_per_layer]

In [32]:
max_idxes_per_truncated_layer = np.argsort(flattened_truncated_all_layers, axis=1)[:, ::-1]

In [33]:
row_indices = np.arange(num_layers)[:, np.newaxis]

In [34]:
flattened_top_interactions_per_layer = flattened_truncated_all_layers[row_indices, max_idxes_per_truncated_layer]

okay now...I need to pick 1 (but make it variable) from first two layers (but make it variable)...actually...I should just export this, then I can load it in somewhere else and use that
okay I'll compute the whole thing now

In [35]:
flattened_top_interactions_per_layer.shape

(11, 603979776)

In [57]:
flattened_top_interactions_per_layer[:,:100:20]

array([[1.0000046 , 0.99999917, 0.9993452 , 0.9990153 , 0.99888736],
       [1.0000058 , 1.0000013 , 0.9999972 , 0.9995525 , 0.9993968 ],
       [1.0000042 , 1.000001  , 0.9999994 , 0.9999982 , 0.9999962 ],
       [1.0000036 , 0.9999995 , 0.9999981 , 0.9999964 , 0.999995  ],
       [1.0000021 , 0.99999857, 0.99999684, 0.99999374, 0.9992907 ],
       [1.0000013 , 0.99999905, 0.99999696, 0.9999952 , 0.9992217 ],
       [1.0000039 , 0.999999  , 0.99999774, 0.99999654, 0.9997192 ],
       [1.0000026 , 0.999999  , 0.9999973 , 0.9999941 , 0.9983443 ],
       [1.0000036 , 0.9999987 , 0.99999624, 0.9999943 , 0.9984486 ],
       [1.0000035 , 0.9999981 , 0.9999959 , 0.999993  , 0.9999852 ],
       [1.0000025 , 0.99999666, 0.9999935 , 0.9999903 , 0.9974637 ]],
      dtype=float32)

# save corresponding idxes to disk


In [52]:
max_idxes_per_truncated_layer[:,:100:20]

array([[356978314, 590018172, 439368734, 496802948,  57512845],
       [544132235, 449495777, 449508140,  14197959, 176767696],
       [ 18134529, 481576069, 321947272, 481569227,  18114772],
       [541109862, 251368918,  41092835, 231578736,  41101241],
       [507216437, 249917586, 493254938,  84938898,   8467131],
       [416538940,  30883652, 305013715, 305013052, 517529786],
       [574429816,  24062264, 568282281, 567997794, 505641027],
       [560074210,  58013357,  58000178, 294993390, 126815326],
       [170930692,  20125171,  20112353, 283446544, 228639571],
       [113364127, 313233541, 283525120, 225744736, 283518312],
       [583102731, 402665739, 583097724, 235351155, 456358114]])

In [60]:
np.unravel_index(max_idxes_per_truncated_layer[:,:100:20][0], shape=(d_sae, d_sae))

(array([14525, 24007, 17877, 20214,  2340]),
 array([11914, 22140, 23582, 23684,  5005]))

In [74]:
cutoff_amount = 1000
top_output_filename = f"../../artefacts/ablations/top_{cutoff_amount}_pearson_per_layer_flattened_feature_idx" 
np.save(top_output_filename, max_idxes_per_truncated_layer[:,:cutoff_amount])

In [71]:
test = np.load(top_output_filename + ".npy")