In [ ]:
# %%

import argparse
import numpy as np
from src.enums import Measure


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
    parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
    parser.add_argument('--save', type=bool, help='whether to save results or not', action=argparse.BooleanOptionalAction, default=False)
    args = parser.parse_args()
    
    print("Reading full interaction scores")
    if args.measure == Measure.pearson:
        filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
        with open(filename, 'rb') as data:
            interaction_scores = np.load(data)['arr_0']
    elif args.measure == Measure.jaccard:
        filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
        with open(filename, 'rb') as data:
            interaction_scores = np.load(data)['arr_0']
    else:
        raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
    num_layers, d_sae, _ = interaction_scores.shape

    flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
    if args.truncate:
        flattened_per_layer_scores = flattened_per_layer_scores[:,:100000]
    
    # key line, very slow
    print("Sorting each layer")
    sorted_by_score_per_layer_pair_idxes = np.argsort(flattened_per_layer_scores, axis=1)

    layer_indices = np.arange(num_layers)[:, np.newaxis]

    num_pairs_to_sample = 1000
    _, curr_num_pairs_per_layer =  sorted_by_score_per_layer_pair_idxes.shape
    lower_bound_idx = int(curr_num_pairs_per_layer * 0.2)
    step_size = (curr_num_pairs_per_layer - lower_bound_idx) // num_pairs_to_sample

    # getting evenly spaced samples, as per https://docs.google.com/document/d/1nTVtRB9qgXsNb0NtERamyvi8a9J8MH1Q2RH17PR3iDo/edit#bookmark=id.nd6kw9yrxctg
    
    output_filename = f"artefacts/sampled_interaction_measures/{args.measure.value}/count_{num_pairs_to_sample}" 

    if args.save:
        print(f"Saving sampled pairs per layer")
        np.save(
            output_filename,
            sorted_by_score_per_layer_pair_idxes[:, lower_bound_idx::step_size]
        )

usage: ipykernel_launcher.py [-h] [--measure MEASURE] [--truncate TRUNCATE]
                             [--save | --no-save]
ipykernel_launcher.py: error: unrecognized arguments: --f=/Users/benlerner/Library/Jupyter/runtime/kernel-v2-89379YvuwkwZMG5Dt.json


SystemExit: 2

/Users/benlerner/work/spar-2024/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
# %% tb

import argparse
import numpy as np
from src.enums import Measure


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
    parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
    parser.add_argument('--save', type=bool, help='whether to save results or not', action=argparse.BooleanOptionalAction, default=False)
    args = parser.parse_args()
    
    print("Reading full interaction scores")
    if args.measure == Measure.pearson:
        filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
        with open(filename, 'rb') as data:
            interaction_scores = np.load(data)['arr_0']
    elif args.measure == Measure.jaccard:
        filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
        with open(filename, 'rb') as data:
            interaction_scores = np.load(data)['arr_0']
    else:
        raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
    num_layers, d_sae, _ = interaction_scores.shape

    flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
    if args.truncate:
        flattened_per_layer_scores = flattened_per_layer_scores[:,:100000]
    
    # key line, very slow
    print("Sorting each layer")
    sorted_by_score_per_layer_pair_idxes = np.argsort(flattened_per_layer_scores, axis=1)

    layer_indices = np.arange(num_layers)[:, np.newaxis]

    num_pairs_to_sample = 1000
    _, curr_num_pairs_per_layer =  sorted_by_score_per_layer_pair_idxes.shape
    lower_bound_idx = int(curr_num_pairs_per_layer * 0.2)
    step_size = (curr_num_pairs_per_layer - lower_bound_idx) // num_pairs_to_sample

    # getting evenly spaced samples, as per https://docs.google.com/document/d/1nTVtRB9qgXsNb0NtERamyvi8a9J8MH1Q2RH17PR3iDo/edit#bookmark=id.nd6kw9yrxctg
    
    output_filename = f"artefacts/sampled_interaction_measures/{args.measure.value}/count_{num_pairs_to_sample}" 

    if args.save:
        print(f"Saving sampled pairs per layer")
        np.save(
            output_filename,
            sorted_by_score_per_layer_pair_idxes[:, lower_bound_idx::step_size]
        )

usage: ipykernel_launcher.py [-h] [--measure MEASURE] [--truncate TRUNCATE]
                             [--save | --no-save]
ipykernel_launcher.py: error: unrecognized arguments: --f=/Users/benlerner/Library/Jupyter/runtime/kernel-v2-89379YvuwkwZMG5Dt.json


SystemExit: 2

In [17]:
import argparse
import numpy as np
from math import prod
from src.enums import Measure

In [3]:
filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
with open(filename, 'rb') as data:
    interaction_scores = np.load(data)['arr_0']

In [8]:
num_layers, d_sae, _ = interaction_scores.shape

flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
if True:
    flattened_per_layer_scores = flattened_per_layer_scores[:,:10000000]

# key line, very slow
print("Sorting each layer")
sorted_by_score_per_layer_pair_idxes = np.argsort(flattened_per_layer_scores, axis=1)

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_by_score_per_layer_pair_idxes.shape
lower_bound_idx = int(curr_num_pairs_per_layer * 0.2)
step_size = (curr_num_pairs_per_layer - lower_bound_idx) // num_pairs_to_sample

Sorting each layer


In [20]:
(np.count_nonzero(flattened_per_layer_scores) / prod(sorted_by_score_per_layer_pair_idxes.shape)) * sorted_by_score_per_layer_pair_idxes.shape[1]

4350.0

In [21]:
interaction_scores.shape

(11, 24576, 24576)

In [ ]:
filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
with open(filename, 'rb') as data:
    interaction_scores = np.load(data)['arr_0']

In [ ]:
d_sae = 24576

In [ ]:
np.unravel_index(foo[0], shape=(d_sae, d_sae))

(array([244, 244, 243, 243, 252, 252, 252, 251, 251, 253, 254, 254, 252,
        253, 249, 249, 249, 248, 248, 250, 250, 249, 249, 249, 233, 233,
        232, 232, 232, 234, 235, 233, 234, 234, 229, 230, 229, 229, 229,
        231, 231, 230, 231, 239, 239, 239, 238, 239, 241, 240, 241, 240,
        240, 236, 236, 236, 235, 235, 237, 238, 238, 236, 237, 373, 373,
        372, 372, 372, 374, 375, 373, 373, 374, 369, 370, 369, 369, 369,
        371, 371, 370, 370, 379, 379, 379, 378, 379, 380, 380, 381, 379,
        380, 376, 376, 376, 375, 375, 377, 378, 378, 376, 377, 360, 360,
        359, 359, 359, 361, 362, 361, 360, 361, 356, 357, 356, 356, 356,
        358, 358, 358, 358, 358, 366, 366, 365, 366, 368, 368, 368, 367,
        367, 363, 363, 363, 362, 363, 365, 365, 365, 364, 364, 398, 398,
        398, 397, 397, 400, 400, 399, 399, 399, 395, 395, 394, 394, 394,
        396, 397, 396, 396, 396, 404, 404, 404, 404, 406, 406, 406, 405,
        406, 401, 401, 401, 400, 401, 403, 403, 403

In [ ]:
np.unravel_index(foo[0], shape=(d_sae, d_sae))[0]

array([244, 244, 243, 243, 252, 252, 252, 251, 251, 253, 254, 254, 252,
       253, 249, 249, 249, 248, 248, 250, 250, 249, 249, 249, 233, 233,
       232, 232, 232, 234, 235, 233, 234, 234, 229, 230, 229, 229, 229,
       231, 231, 230, 231, 239, 239, 239, 238, 239, 241, 240, 241, 240,
       240, 236, 236, 236, 235, 235, 237, 238, 238, 236, 237, 373, 373,
       372, 372, 372, 374, 375, 373, 373, 374, 369, 370, 369, 369, 369,
       371, 371, 370, 370, 379, 379, 379, 378, 379, 380, 380, 381, 379,
       380, 376, 376, 376, 375, 375, 377, 378, 378, 376, 377, 360, 360,
       359, 359, 359, 361, 362, 361, 360, 361, 356, 357, 356, 356, 356,
       358, 358, 358, 358, 358, 366, 366, 365, 366, 368, 368, 368, 367,
       367, 363, 363, 363, 362, 363, 365, 365, 365, 364, 364, 398, 398,
       398, 397, 397, 400, 400, 399, 399, 399, 395, 395, 394, 394, 394,
       396, 397, 396, 396, 396, 404, 404, 404, 404, 406, 406, 406, 405,
       406, 401, 401, 401, 400, 401, 403, 403, 403, 402, 402, 38

In [ ]:
np.unique(np.unravel_index(foo[0], shape=(d_sae, d_sae))[0], return_counts=True)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [ ]:
np.unravel_index(foo[0], shape=(d_sae, d_sae))[0][-1]

135

In [ ]:
np.unravel_index(foo[0], shape=(d_sae, d_sae))[1][-1]

20319

In [ ]:
interaction_scores[0][135][20319]

0.0

In [ ]:
interaction_scores.shape

(11, 24576, 24576)

In [ ]:
(np.unravel_index(foo[0], shape=(d_sae, d_sae))[0][0], np.unravel_index(foo[0], shape=(d_sae, d_sae))[0][-1])

(244, 135)

In [ ]:
foo

array([[6000195, 6005946, 5984493, ..., 3349818, 3322551, 3338079],
       [6000378, 6005899, 5984454, ..., 3349807, 3322422, 3335716],
       [6000294, 6005739, 5983985, ..., 3348752, 3322192, 3336923],
       ...,
       [5999275, 6005011, 5983553, ..., 3352331, 3322375, 3331775],
       [5999058, 6004809, 5983354, ..., 3352306, 3322241, 3332726],
       [5999338, 6004861, 5983709, ..., 3352456, 3321478, 3331805]])

In [ ]:
first_layer_first_idx, first_layer_second_idx = np.unravel_index(foo[0], shape=(d_sae, d_sae))

In [ ]:
first_layer_first_idx

array([244, 244, 243, 243, 252, 252, 252, 251, 251, 253, 254, 254, 252,
       253, 249, 249, 249, 248, 248, 250, 250, 249, 249, 249, 233, 233,
       232, 232, 232, 234, 235, 233, 234, 234, 229, 230, 229, 229, 229,
       231, 231, 230, 231, 239, 239, 239, 238, 239, 241, 240, 241, 240,
       240, 236, 236, 236, 235, 235, 237, 238, 238, 236, 237, 373, 373,
       372, 372, 372, 374, 375, 373, 373, 374, 369, 370, 369, 369, 369,
       371, 371, 370, 370, 379, 379, 379, 378, 379, 380, 380, 381, 379,
       380, 376, 376, 376, 375, 375, 377, 378, 378, 376, 377, 360, 360,
       359, 359, 359, 361, 362, 361, 360, 361, 356, 357, 356, 356, 356,
       358, 358, 358, 358, 358, 366, 366, 365, 366, 368, 368, 368, 367,
       367, 363, 363, 363, 362, 363, 365, 365, 365, 364, 364, 398, 398,
       398, 397, 397, 400, 400, 399, 399, 399, 395, 395, 394, 394, 394,
       396, 397, 396, 396, 396, 404, 404, 404, 404, 406, 406, 406, 405,
       406, 401, 401, 401, 400, 401, 403, 403, 403, 402, 402, 38

In [ ]:
interaction_scores[0][first_layer_first_idx][first_layer_second_idx]

IndexError: index 3651 is out of bounds for axis 0 with size 1000

In [ ]:
interaction_scores[0,first_layer_first_idx,first_layer_second_idx]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
interaction_scores[0,first_layer_first_idx,first_layer_second_idx].count_nonzero()

AttributeError: 'numpy.ndarray' object has no attribute 'count_nonzero'

In [ ]:
np.count_nonzero(interaction_scores[0,first_layer_first_idx,first_layer_second_idx])

0

In [ ]:
flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
flattened_per_layer_scores = flattened_per_layer_scores[:,:10000000]

NameError: name 'num_layers' is not defined

In [ ]:
num_layers, d_sae, _ = interaction_scores.shape

In [ ]:
flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
flattened_per_layer_scores = flattened_per_layer_scores[:,:10000000]

In [ ]:
flattened_per_layer_scores.shape

(11, 10000000)

In [ ]:
np.count_nonzero(flattened_per_layer_scores)

47850