In [ ]:
filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
with open(filename, 'rb') as data:interaction_scores = np.load(data)['arr_0']

NameError: name 'np' is not defined

In [ ]:
# %% tb

import argparse
import numpy as np
from src.enums import Measure


from dataclasses import dataclass

@dataclass
class Args:
    measure: Measure = Measure.pearson
    truncate: bool = True
    save: bool = False

In [ ]:
# %%

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
#     parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
#     parser.add_argument('--save', type=bool, help='whether to save results or not', default=False)
#     args = parser.parse_args()


args = Args() 
print("Reading full interaction scores")
if args.measure == Measure.pearson:
    filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
elif args.measure == Measure.jaccard:
    filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
else:
    raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
num_layers, d_sae, _ = interaction_scores.shape

flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
if args.truncate:
    flattened_per_layer_scores = flattened_per_layer_scores[:,:10000000]

# key line, very slow
print("Sorting each layer")
sorted_by_score_per_layer_pair_idxes = np.argsort(flattened_per_layer_scores, axis=1)

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_by_score_per_layer_pair_idxes.shape
lower_bound_idx = int(curr_num_pairs_per_layer * 0.2)
step_size = (curr_num_pairs_per_layer - lower_bound_idx) // num_pairs_to_sample

# getting evenly spaced samples, as per https://docs.google.com/document/d/1nTVtRB9qgXsNb0NtERamyvi8a9J8MH1Q2RH17PR3iDo/edit#bookmark=id.nd6kw9yrxctg

output_filename = f"artefacts/sampled_interaction_measures/{args.measure.value}/count_{num_pairs_to_sample}" 

if args.save:
    print(f"Saving sampled pairs per layer")
    np.save(
        output_filename,
        sorted_by_score_per_layer_pair_idxes[:, lower_bound_idx::step_size]
    )

Reading full interaction scores
Sorting each layer


In [ ]:
output_filename

'artefacts/sampled_interaction_measures/pearson_correlation/count_1000'

In [ ]:
# %% tb

import argparse
import numpy as np
from math import prod
from src.enums import Measure


from dataclasses import dataclass

@dataclass
class Args:
    measure: Measure = Measure.pearson
    truncate: bool = True
    save: bool = False

In [ ]:
# %%

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_desc_by_score_per_layer_pair_idxes.shape
# get the nonzero percent on avg across all layers
nonzero_percent = np.count_nonzero(flattened_per_layer_scores) / prod(flattened_per_layer_scores.shape)

# try to only sample from the nonzero entries by having the same lower bound idx across all layers
# since they're sorted in descending order by score, this'll be the right bound
last_non_zero_idx = int(nonzero_percent * curr_num_pairs_per_layer)
assert last_non_zero_idx <= 1, "Not enough nonzero scores. Loosen the truncation"
step_size = (curr_num_pairs_per_layer - last_non_zero_idx) // num_pairs_to_sample

NameError: name 'sorted_desc_by_score_per_layer_pair_idxes' is not defined

In [ ]:
# %%

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_desc_by_score_per_layer_pair_idxes.shape
# get the nonzero percent on avg across all layers
nonzero_percent = np.count_nonzero(flattened_per_layer_scores) / prod(flattened_per_layer_scores.shape)

# try to only sample from the nonzero entries by having the same lower bound idx across all layers
# since they're sorted in descending order by score, this'll be the right bound
last_non_zero_idx = int(nonzero_percent * curr_num_pairs_per_layer)
assert last_non_zero_idx <= 1, "Not enough nonzero scores. Loosen the truncation"
step_size = (curr_num_pairs_per_layer - last_non_zero_idx) // num_pairs_to_sample

NameError: name 'sorted_desc_by_score_per_layer_pair_idxes' is not defined

In [ ]:
# %%

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
#     parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
#     parser.add_argument('--save', type=bool, help='whether to save results or not', default=False)
#     args = parser.parse_args()


args = Args()
print("Reading full interaction scores")
if args.measure == Measure.pearson:
    filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
elif args.measure == Measure.jaccard:
    filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
else:
    raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
num_layers, d_sae, _ = interaction_scores.shape

flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)
if args.truncate:
    flattened_per_layer_scores = flattened_per_layer_scores[:,:10000000]

# key line, very slow
print("Sorting each layer")
# the indexes of the layer pairs, per layer, sorted by the score of each pair, descending
sorted_desc_by_score_per_layer_pair_idxes = np.argsort(flattened_per_layer_scores, axis=1)[::-1]

Reading full interaction scores
Sorting each layer


In [ ]:
# %%

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_desc_by_score_per_layer_pair_idxes.shape
# get the nonzero percent on avg across all layers
nonzero_percent = np.count_nonzero(flattened_per_layer_scores) / prod(flattened_per_layer_scores.shape)

# try to only sample from the nonzero entries by having the same lower bound idx across all layers
# since they're sorted in descending order by score, this'll be the right bound
last_non_zero_idx = int(nonzero_percent * curr_num_pairs_per_layer)
assert last_non_zero_idx <= 1, "Not enough nonzero scores. Loosen the truncation"
step_size = (curr_num_pairs_per_layer - last_non_zero_idx) // num_pairs_to_sample

AssertionError: Not enough nonzero scores. Loosen the truncation

In [ ]:
nonzero_percent

0.000435

In [ ]:
curr_num_pairs_per_layer

10000000

In [ ]:
last_non_zero_idx

4350

In [ ]:
int(nonzero_percent * curr_num_pairs_per_layer)

4350

In [ ]:
# %%

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_desc_by_score_per_layer_pair_idxes.shape
# get the nonzero percent on avg across all layers
nonzero_percent = np.count_nonzero(flattened_per_layer_scores) / prod(flattened_per_layer_scores.shape)

# try to only sample from the nonzero entries by having the same lower bound idx across all layers
# since they're sorted in descending order by score, this'll be the right bound
last_non_zero_idx = int(nonzero_percent * curr_num_pairs_per_layer)
assert last_non_zero_idx >= 1, "Not enough nonzero scores. Loosen the truncation"
step_size = (curr_num_pairs_per_layer - last_non_zero_idx) // num_pairs_to_sample

In [ ]:
step_size

9995

In [ ]:
# %%

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_desc_by_score_per_layer_pair_idxes.shape
# get the nonzero percent on avg across all layers
nonzero_percent = np.count_nonzero(flattened_per_layer_scores) / prod(flattened_per_layer_scores.shape)

# try to only sample from the nonzero entries by having the same lower bound idx across all layers
# since they're sorted in descending order by score, this'll be the right bound
last_non_zero_idx = int(nonzero_percent * curr_num_pairs_per_layer)
assert last_non_zero_idx >= 1, "Not enough nonzero scores. Loosen the truncation"
step_size = (curr_num_pairs_per_layer - last_non_zero_idx) // num_pairs_to_sample

evenly_spaced_by_score_idxes = sorted_desc_by_score_per_layer_pair_idxes[:, :last_non_zero_idx:step_size]

In [ ]:
evenly_spaced_by_score_idxes

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [ ]:
# %%

layer_indices = np.arange(num_layers)[:, np.newaxis]

num_pairs_to_sample = 1000
_, curr_num_pairs_per_layer =  sorted_desc_by_score_per_layer_pair_idxes.shape
# get the nonzero percent on avg across all layers
nonzero_percent = np.count_nonzero(flattened_per_layer_scores) / prod(flattened_per_layer_scores.shape)

# try to only sample from the nonzero entries by having the same lower bound idx across all layers
# since they're sorted in descending order by score, this'll be the right bound
last_non_zero_idx = int(nonzero_percent * curr_num_pairs_per_layer)
assert last_non_zero_idx >= 1, "Not enough nonzero scores. Loosen the truncation"
step_size = last_non_zero_idx // num_pairs_to_sample

evenly_spaced_by_score_idxes = sorted_desc_by_score_per_layer_pair_idxes[:, :last_non_zero_idx:step_size]

In [ ]:
evenly_spaced_by_score_idxes

array([[      0, 6665732, 6665736, ..., 6667593, 6667615, 6667487],
       [      0, 6665664, 6665668, ..., 6667524, 6667546, 6667418],
       [      0, 6665677, 6665681, ..., 6667537, 6667559, 6667431],
       ...,
       [      0, 6666116, 6666120, ..., 6667974, 6667979, 6667868],
       [      0, 6666241, 6666245, ..., 6668099, 6668104, 6667993],
       [      0, 6666280, 6666284, ..., 6668138, 6668143, 6668032]])

In [ ]:
evenly_spaced_by_score_idxes.shape

(11, 1088)

In [ ]:
evenly_spaced_by_score_idxes[0]

array([      0, 6665732, 6665736, ..., 6667593, 6667615, 6667487])

In [ ]:
evenly_spaced_by_score_idxes[0].unravel_index()

AttributeError: 'numpy.ndarray' object has no attribute 'unravel_index'

In [ ]:
np.unravel_index(evenly_spaced_by_score_idxes[0], (d_sae, d_sae))

(array([  0, 271, 271, ..., 271, 271, 271]),
 array([   0, 5636, 5640, ..., 7497, 7519, 7391]))

In [ ]:
interaction_scores[0, 271, 5636]

0.0

In [ ]:
sorted_desc_by_score_per_layer_pair_idxes

array([[      0, 6665729, 6665730, ..., 8123505, 5908041, 3487047],
       [      0, 6665661, 6665662, ..., 4556750, 1652166, 8329835],
       [      0, 6665674, 6665675, ..., 2372202, 6360067, 5929546],
       ...,
       [      0, 6666113, 6666114, ...,  377879, 5856433, 6616806],
       [      0, 6666238, 6666239, ..., 1908935, 3002631, 2165419],
       [      0, 6666277, 6666278, ..., 6504290, 8625835,  428763]])

In [ ]:
flattened_per_layer_scores

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
np.count_nonzero(flattened_per_layer_scores)

47850

In [ ]:
flattened_per_layer_scores.shape

(11, 10000000)

In [ ]:
dim1 = evenly_spaced_by_score_idxes[0] // d_sae

In [ ]:
dim1 = evenly_spaced_by_score_idxes[0] % d_sae

In [ ]:
dim1 = evenly_spaced_by_score_idxes[0] // d_sae

In [ ]:
dim2 = evenly_spaced_by_score_idxes[0] % d_sae

In [ ]:
dim1

array([  0, 271, 271, ..., 271, 271, 271])

In [ ]:
dim2

array([   0, 5636, 5640, ..., 7497, 7519, 7391])

In [ ]:
np.unique(dim1, return_counts=True)

(array([  0, 271]), array([   1, 1087]))

In [ ]:
dim1 = evenly_spaced_by_score_idxes[0] // d_sae

In [ ]:
np.unique(dim1, return_counts=True)

(array([  0, 271]), array([   1, 1087]))

In [ ]:
np.vstack([dim1, dim2])

array([[   0,  271,  271, ...,  271,  271,  271],
       [   0, 5636, 5640, ..., 7497, 7519, 7391]])

In [ ]:
flattened_per_layer_scores[0, 271, 5636]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
interaction_scores[0, 271, 5636]

0.0

In [ ]:
# %%

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
#     parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
#     parser.add_argument('--save', type=bool, help='whether to save results or not', default=False)
#     args = parser.parse_args()


args = Args()
print("Reading full interaction scores")
if args.measure == Measure.pearson:
    filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
elif args.measure == Measure.jaccard:
    filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
else:
    raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
num_layers, d_sae, _ = interaction_scores.shape

Reading full interaction scores


In [ ]:
interaction_scores.reshape(num_layers, d_sae**2)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
interaction_scores.reshape(num_layers, d_sae**2)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
10000000

10000000

In [ ]:
interaction_scores.shape[1]

24576

In [ ]:
d_sae**2

603979776

In [ ]:
10000000

10000000

In [ ]:
flattened_per_layer_scores = interaction_scores.reshape(num_layers, d_sae**2)

In [ ]:
flattened_per_layer_scores[0].shape

(603979776,)

In [ ]:
np.argsort(flattened_per_layer_scores[0])

array([337327719, 337315087, 337315280, ..., 467889802, 356989137,
       356978314])

In [ ]:
# %%

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
#     parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
#     parser.add_argument('--save', type=bool, help='whether to save results or not', default=False)
#     args = parser.parse_args()


args = Args()
print("Reading full interaction scores")
if args.measure == Measure.pearson:
    filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
elif args.measure == Measure.jaccard:
    filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
else:
    raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
num_layers, d_sae, _ = interaction_scores.shape

KeyboardInterrupt: 

In [ ]:
# %% tb

import argparse
import numpy as np
from math import prod
from src.enums import Measure
from joblib import Parallel, delayed


from dataclasses import dataclass

@dataclass
class Args:
    measure: Measure = Measure.pearson
    truncate: bool = True
    save: bool = False

In [ ]:
 sorted_desc_by_score_per_layer_pair_idxes = np.array(Parallel(n_jobs=-1)(delayed(np.argsort)(row) for row in  interaction_scores.reshape(num_layers, d_sae**2)))

0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0

KeyboardInterrupt: 

In [ ]:
interaction_scores

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
flattened_scores = interaction_scores.reshape(num_layers, d_sae**2)

In [ ]:
argsorted_idxes = np.argsort(flattened_scores, axis=1)[::-1]

In [ ]:
argsorted_idxes

NameError: name 'argsorted_idxes' is not defined

In [ ]:
np.save("artefacts/sampled_interaction_measures/full_sorted_flattened_pearson_idxes", argsorted_idxes)

In [ ]:
# %% tb

import argparse
import numpy as np
from math import prod
from src.enums import Measure
from joblib import Parallel, delayed


from dataclasses import dataclass

@dataclass
class Args:
    measure: Measure = Measure.pearson
    truncate: bool = True
    save: bool = False

In [ ]:
# %%

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--measure', type=Measure, help='interaction measure whose values will indicate the', default=Measure.pearson)
#     parser.add_argument('--truncate', type=bool, help='truncates the number of feature pairs that are sampled, used only for testing bc its fast', default=False)
#     parser.add_argument('--save', type=bool, help='whether to save results or not', default=False)
#     args = parser.parse_args()


args = Args()
print("Reading full interaction scores")
if args.measure == Measure.pearson:
    filename = "artefacts/similarity_measures/pearson_correlation/res_jb_sae_feature_similarity_pearson_correlation_1M_0.0_0.1.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
elif args.measure == Measure.jaccard:
    filename = "artefacts/jaccard/jaccard_2024-07-02-a.npz"
    with open(filename, 'rb') as data:
        interaction_scores = np.load(data)['arr_0']
else:
    raise NotImplementedError(f"Haven't gotten around to {args.measure} yet")
num_layers, d_sae, _ = interaction_scores.shape

Reading full interaction scores


In [ ]:
flattened_scores = interaction_scores.reshape(num_layers, d_sae**2)

In [ ]:
argsorted_idxes = np.argsort(flattened_scores, axis=1)[::-1]


In [ ]:
argsorted_idxes[0]

array([ 86993927,         0, 402596938, ..., 482069506, 583098208,
       583102731])

In [ ]:
flattened_scores[argsorted_idxes[0]]

MemoryError: Unable to allocate 1.27 EiB for an array with shape (603979776, 603979776) and data type float32

In [ ]:
flattened_scores[0][argsorted_idxes[0]]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
flattened_scores[0][argsorted_idxes[0][0]]

0.0

In [ ]:
argsorted_idxes

array([[ 86993927,         0, 402596938, ..., 482069506, 583098208,
        583102731],
       [142740947, 198705344, 295824851, ..., 540765343, 113348780,
        113364127],
       [        0, 402594202, 402594201, ..., 435466756, 170948083,
        170930692],
       ...,
       [        0, 402626472, 402626471, ..., 481572846, 481576948,
         18134529],
       [543614872, 233170840, 171457596, ..., 292799615, 558785663,
        544132235],
       [337327719, 337315087, 337315280, ..., 467889802, 356989137,
        356978314]])

In [ ]:
argsorted_idxes[0]

array([ 86993927,         0, 402596938, ..., 482069506, 583098208,
       583102731])

In [ ]:
flattened_scores[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
np.count_nonzero(flattened_scores[0])

172752

In [ ]:
d_sae**2

603979776

In [ ]:
np.count_nonzero(flattened_scores)

2874881

In [ ]:
2874881/603979776

0.004759896132681105

In [ ]:
flattened_scores

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
interaction_scores

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
interaction_scores.shape

(11, 24576, 24576)

In [ ]:
flattened_scores.shape

(11, 603979776)

In [ ]:
fake_data = 100 * [0] + [0.1, 0.2, 0.3, 0.35]

In [ ]:
fake_data

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.1,
 0.2,
 0.3,
 0.35]

In [ ]:
argsorted_idxes

array([[ 86993927,         0, 402596938, ..., 482069506, 583098208,
        583102731],
       [142740947, 198705344, 295824851, ..., 540765343, 113348780,
        113364127],
       [        0, 402594202, 402594201, ..., 435466756, 170948083,
        170930692],
       ...,
       [        0, 402626472, 402626471, ..., 481572846, 481576948,
         18134529],
       [543614872, 233170840, 171457596, ..., 292799615, 558785663,
        544132235],
       [337327719, 337315087, 337315280, ..., 467889802, 356989137,
        356978314]])

In [ ]:
argsorted_idxes = np.argsort(flattened_scores, axis=1)

In [ ]:
fake_data

Traceback (most recent call last):
  File "/Users/benlerner/work/spar-2024/.venv/lib/python3.12/site-packages/IPython/core/completer.py", line 3171, in _complete
    result = matcher(context)
             ^^^^^^^^^^^^^^^^
  File "/Users/benlerner/work/spar-2024/.venv/lib/python3.12/site-packages/IPython/core/completer.py", line 2099, in magic_matcher
    matches = self.magic_matches(text)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benlerner/work/spar-2024/.venv/lib/python3.12/site-packages/IPython/core/completer.py", line 2132, in magic_matches
    global_matches = self.global_matches(bare_text)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benlerner/work/spar-2024/.venv/lib/python3.12/site-packages/IPython/core/completer.py", line 1113, in global_matches
    for word in lst:
RuntimeError: dictionary changed size during iteration


[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.1,
 0.2,
 0.3,
 0.35]

In [ ]:
np.count_nonzero(flattened_scores) / prod(flattened_scores)

KeyboardInterrupt: 

In [ ]:
proportion_nonzero = np.count_nonzero(flattened_scores) / prod(flattened_scores.shape)

In [ ]:
proportion_nonzero

0.0004327178302437368

In [ ]:
argsorted_idxes[0]

array([337327719, 337315087, 337315280, ..., 467889802, 356989137,
       356978314])

In [ ]:
flattened_scores[0][argsorted_idxes[0][-1]]

1.0000046

In [ ]:
flattened_scores[0][argsorted_idxes[0][-100]]

0.9987882

In [ ]:
flattened_scores[0][argsorted_idxes[0][-10000]]

0.90520793

In [ ]:
proportion_nonzero * (d_sae * d_sae)

261352.81818181818

In [ ]:
flattened_scores[0][argsorted_idxes[0][-]]

SyntaxError: invalid syntax (<ipython-input-34-ef97157edb7d>, line 1)

In [ ]:
cutoff_idx = int(proportion_nonzero * (d_sae * d_sae))

In [ ]:
flattened_scores[0][argsorted_idxes[0][-cutoff_idx]]

0.0

In [ ]:
flattened_scores[0][argsorted_idxes[0][-cutoff_idx+100]]

0.0

In [ ]:
flattened_scores[0][argsorted_idxes[0][-cutoff_idx+1000]]

0.0

In [ ]:
flattened_scores[0][argsorted_idxes[0][-cutoff_idx+100000]]

0.105261624

In [ ]:
flattened_scores[0][argsorted_idxes[0][-cutoff_idx+60000]]

0.0

In [ ]:
fake_data

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.1,
 0.2,
 0.3,
 0.35]

In [ ]:
fake_data[-10:]

[0, 0, 0, 0, 0, 0, 0.1, 0.2, 0.3, 0.35]

In [ ]:
desc_argsorted_idxes = argsorted_idxes[:, ::-1]

In [ ]:
desc_argsorted_idxes

array([[356978314, 356989137, 467889802, ..., 337315280, 337315087,
        337327719],
       [544132235, 558785663, 292799615, ..., 171457596, 233170840,
        543614872],
       [ 18134529, 481576948, 481572846, ..., 402626471, 402626472,
                0],
       ...,
       [170930692, 170948083, 435466756, ..., 402594201, 402594202,
                0],
       [113364127, 113348780, 540765343, ..., 295824851, 198705344,
        142740947],
       [583102731, 583098208, 482069506, ..., 402596938,         0,
         86993927]])

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][0]]

1.0000046

In [ ]:
per_layer_nonzero = np.count_nonzero(flattened_scores, axis=1)

In [ ]:
per_layer_nonzero.shape

(11,)

In [ ]:
per_layer_nonzero

array([172752, 165573, 165466, 197123, 238215, 271127, 303428, 334352,
       357107, 341060, 328678])

In [ ]:
# I can just use these directly as the index! duh! no need to sort

In [ ]:
desc_argsorted_idxes[0][per_layer_nonzero[0]]

201173474

In [ ]:
flattened_scores[desc_argsorted_idxes[0][per_layer_nonzero[0]]]

IndexError: index 201173474 is out of bounds for axis 0 with size 11

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]]]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]]-1]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]]-100]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]]-10000]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]]-1000000]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]-100]]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]-10000]]

0.10458563

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]-1000]]

0.10037219

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]-100]]

0.0

In [ ]:
flattened_scores[0][desc_argsorted_idxes[0][per_layer_nonzero[0]-500]]

0.1001482

In [ ]:
desc_argsorted_idxes

array([[356978314, 356989137, 467889802, ..., 337315280, 337315087,
        337327719],
       [544132235, 558785663, 292799615, ..., 171457596, 233170840,
        543614872],
       [ 18134529, 481576948, 481572846, ..., 402626471, 402626472,
                0],
       ...,
       [170930692, 170948083, 435466756, ..., 402594201, 402594202,
                0],
       [113364127, 113348780, 540765343, ..., 295824851, 198705344,
        142740947],
       [583102731, 583098208, 482069506, ..., 402596938,         0,
         86993927]])

In [ ]:
num_scores_to_sample_per_layer = 10

In [ ]:
step_sizes = per_layer_nonzero // 10

In [ ]:
step_sizes

array([17275, 16557, 16546, 19712, 23821, 27112, 30342, 33435, 35710,
       34106, 32867])

In [ ]:
desc_argsorted_idxes[:, :per_layer_nonzero:step_sizes]

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
per_layer_nonzero

array([172752, 165573, 165466, 197123, 238215, 271127, 303428, 334352,
       357107, 341060, 328678])

In [ ]:
step_sizes

array([17275, 16557, 16546, 19712, 23821, 27112, 30342, 33435, 35710,
       34106, 32867])

In [ ]:
sampled_data = np.array(
    [
        desc_argsorted_idxes[layer, :end:step] for layer, (end, step) in enumerate(zip(per_layer_nonzero, step_sizes))
    ]
)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (11,) + inhomogeneous part.

In [ ]:
num_elements_per_layer = (end_idxes - start_idxes) // step_sizes

NameError: name 'end_idxes' is not defined

In [ ]:
step_sizes

array([17275, 16557, 16546, 19712, 23821, 27112, 30342, 33435, 35710,
       34106, 32867])

In [ ]:
end_idxes = num_scores_to_sample_per_layer * step_sizes

In [ ]:
end_idxes

array([172750, 165570, 165460, 197120, 238210, 271120, 303420, 334350,
       357100, 341060, 328670])

In [ ]:
sampled_data = np.array(
    [
        desc_argsorted_idxes[layer, :end:step] for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))
    ]
)

In [ ]:
sampled_data

array([[356978314, 291845608, 486693340,  23059239, 271265440, 340955003,
        541184995, 237850858,  46929383, 384496104],
       [544132235, 263472000, 426954070,  15874444, 438506111, 357310975,
        328398199,  86423441, 322231541, 449587590],
       [ 18134529,   2307214, 149933803, 240851699, 319204554,  19288764,
        411347663, 402144299, 515245395, 443472835],
       [541109862, 481984919, 593426447, 183282110, 373446634, 601787635,
         69813037, 408567325, 134527085,   7154575],
       [507216437, 340636636, 578055568, 409689865, 432642777, 502107666,
        475395493, 504066393,  56754008, 144713010],
       [416538940, 331154172, 340831456, 477391032, 578339100, 535175781,
        584189485, 132934959, 301432712,  26445462],
       [574429816, 160202541, 602933552, 265694414,  94076108, 584381479,
        263699079, 242837990,  28719551, 454120294],
       [560074210, 521579010, 435676314, 183297395,  61041832, 541470752,
        549982207, 529571878, 4399623

In [ ]:
sampled_idxes = np.array(
    [
        desc_argsorted_idxes[layer, :end:step] for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))
    ]
)

In [ ]:
sampled_idxes[0]

array([356978314, 291845608, 486693340,  23059239, 271265440, 340955003,
       541184995, 237850858,  46929383, 384496104])

In [ ]:
flattened_scores[0][sampled_idxes[0]]

array([1.0000046 , 0.6236895 , 0.34123915, 0.2480272 , 0.19902335,
       0.16865902, 0.14695911, 0.13084902, 0.11825435, 0.10817938],
      dtype=float32)

In [ ]:
interaction_scores

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
interaction_scores.shape

(11, 24576, 24576)

In [ ]:
interaction_scores[0][230][500]

0.0

In [ ]:
result = []

In [ ]:
fake_data

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.1,
 0.2,
 0.3,
 0.35]

In [ ]:
fake_data = fake_data[-12:]

In [ ]:
fake_data

[0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2, 0.3, 0.35]

In [ ]:
flattened_scores

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
flattened_scores.shape

(11, 603979776)

In [ ]:
fake_data

[0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2, 0.3, 0.35]

In [ ]:
desc_argsorted_idxes[0]

array([356978314, 356989137, 467889802, ..., 337315280, 337315087,
       337327719])

In [ ]:
per_layer_nonzero

array([172752, 165573, 165466, 197123, 238215, 271127, 303428, 334352,
       357107, 341060, 328678])

In [ ]:
d_sae**2

603979776

In [ ]:
end_idxes

array([172750, 165570, 165460, 197120, 238210, 271120, 303420, 334350,
       357100, 341060, 328670])

In [ ]:
step_sizes

array([17275, 16557, 16546, 19712, 23821, 27112, 30342, 33435, 35710,
       34106, 32867])

In [ ]:
result

[]

In [ ]:
sampled_idxes

array([[356978314, 291845608, 486693340,  23059239, 271265440, 340955003,
        541184995, 237850858,  46929383, 384496104],
       [544132235, 263472000, 426954070,  15874444, 438506111, 357310975,
        328398199,  86423441, 322231541, 449587590],
       [ 18134529,   2307214, 149933803, 240851699, 319204554,  19288764,
        411347663, 402144299, 515245395, 443472835],
       [541109862, 481984919, 593426447, 183282110, 373446634, 601787635,
         69813037, 408567325, 134527085,   7154575],
       [507216437, 340636636, 578055568, 409689865, 432642777, 502107666,
        475395493, 504066393,  56754008, 144713010],
       [416538940, 331154172, 340831456, 477391032, 578339100, 535175781,
        584189485, 132934959, 301432712,  26445462],
       [574429816, 160202541, 602933552, 265694414,  94076108, 584381479,
        263699079, 242837990,  28719551, 454120294],
       [560074210, 521579010, 435676314, 183297395,  61041832, 541470752,
        549982207, 529571878, 4399623

In [ ]:
def get_sampled_idxes(desc_argsorted_idxes_, num_samples_per_layer: int):
    count_nonzero_per_layer = np.count_nonzero(desc_argsorted_idxes_, axis=1)
    step_sizes = count_nonzero_per_layer // num_samples_per_layer
    assert min(step_sizes) > 0, "count_nonzero < num_samples"
    end_idxes = step_sizes * num_samples_per_layer
    return np.array(
        [
            desc_argsorted_idxes_[layer, :end:step]
            for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))
        ]
    )
    

In [ ]:
sampled_idxes_2 = get_sampled_idxes(desc_argsorted_idxes)

TypeError: get_sampled_idxes() missing 1 required positional argument: 'num_samples_per_layer'

In [ ]:
sampled_idxes_2 = get_sampled_idxes(desc_argsorted_idxes, 1000)

In [ ]:
sampled_idxes_2

array([[356978314, 201399193, 200979598, ..., 402067261, 401434908,
        403220124],
       [544132235, 201402777, 200843101, ..., 402067416, 401435287,
        403218961],
       [ 18134529, 201496736, 200978588, ..., 402067964, 401436073,
        403219832],
       ...,
       [170930692, 201604984, 201133774, ..., 402037280, 401404520,
        403187723],
       [113364127, 201376754, 201122782, ..., 402038465, 401407224,
        403190441],
       [583102731, 201596464, 200649424, ..., 402038469, 401407287,
        403190349]])

In [ ]:
sampled_idxes_2.shape

(11, 1000)

In [ ]:
flattened_per_layer_scores[0][sampled_idxes_2[0]]

NameError: name 'flattened_per_layer_scores' is not defined

In [ ]:
flattened_scores[0][sampled_idxes_2[0]]

array([1.0000046, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 

In [ ]:
flattened_scores[0].shape

(603979776,)

In [ ]:
flattened_scores[0][sampled_idxes_2[0][0]]

1.0000046

In [ ]:
flattened_scores[0][sampled_idxes_2[0][2]]

0.0

In [ ]:
per_layer_nonzero // 1000

array([172, 165, 165, 197, 238, 271, 303, 334, 357, 341, 328])

In [ ]:
"""    count_nonzero_per_layer = np.count_nonzero(desc_argsorted_idxes_, axis=1)
    step_sizes = count_nonzero_per_layer // num_samples_per_layer
    assert min(step_sizes) > 0, "count_nonzero < num_samples"
    end_idxes = step_sizes * num_samples_per_layer
    return np.array(
        [
            desc_argsorted_idxes_[layer, :end:step]
            for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))
        ]
    )"""

'    count_nonzero_per_layer = np.count_nonzero(desc_argsorted_idxes_, axis=1)\n    step_sizes = count_nonzero_per_layer // num_samples_per_layer\n    assert min(step_sizes) > 0, "count_nonzero < num_samples"\n    end_idxes = step_sizes * num_samples_per_layer\n    return np.array(\n        [\n            desc_argsorted_idxes_[layer, :end:step]\n            for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))\n        ]\n    )'

In [ ]:
step_sizes = per_layer_nonzero // 1000

In [ ]:
end_idxes = step_sizes * 1000

In [ ]:
foo = np.array(
        [
            desc_argsorted_idxes_[layer, :end:step]
            for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))
        ]
)

NameError: name 'desc_argsorted_idxes_' is not defined

In [ ]:
foo = np.array(
        [
            desc_argsorted_idxes[layer, :end:step]
            for layer, (end, step) in enumerate(zip(end_idxes, step_sizes))
        ]
)

In [ ]:
foo[0]

array([356978314, 232045703, 214254781, 187009911,  38235733,  55265429,
       591477988, 149341116, 530167203, 459884629, 573379863, 252071316,
       253481736, 369017362, 206604511, 460630083,  24057730, 598718917,
        39122578, 140125064, 104959807, 504494929, 183036432, 219946922,
       508538821,  62175024, 238999536, 103280495, 325045466, 452712263,
       441681670, 467662009, 331522955,  42385987, 483290526, 378976949,
       517234587, 385313271, 578790942, 183449620, 301989941,  95798303,
       351914511, 112580365, 197188834, 354900622, 556069593, 437924407,
       580582785, 601909935, 534407410,  99559610, 381090515,  13382411,
       116354485, 582858644, 589084244, 358797355,   3252632, 480036035,
       274155770, 260861539, 417526506, 297516462,  56101762, 145105725,
       199179639, 422077014, 501690244, 302508426, 319103042,  91111057,
       445648525,  98208924, 109616785, 194737011, 601521390, 598517945,
       159765167, 324819114, 537534639, 302967900, 

In [ ]:
flattened_scores[0][356978314]

1.0000046

In [ ]:
flattened_scores[0][232045703]

0.998426

In [ ]:
flattened_scores[0, foo[0]]

array([1.0000046 , 0.998426  , 0.9975997 , 0.99691534, 0.9963178 ,
       0.99577004, 0.9951938 , 0.99464273, 0.99406564, 0.9935037 ,
       0.99284315, 0.99224174, 0.99155235, 0.9908814 , 0.9902493 ,
       0.98964685, 0.98890775, 0.9881254 , 0.9873074 , 0.98646295,
       0.98563635, 0.9848198 , 0.9840154 , 0.98316574, 0.98230577,
       0.9812562 , 0.9801698 , 0.9791283 , 0.97809917, 0.9769713 ,
       0.9758131 , 0.97463703, 0.97324437, 0.9720334 , 0.9706463 ,
       0.96911424, 0.96758306, 0.9659832 , 0.96435106, 0.9626126 ,
       0.96078193, 0.95906293, 0.9569604 , 0.95469725, 0.9526079 ,
       0.9504701 , 0.9478901 , 0.94538134, 0.9426415 , 0.93972796,
       0.93669665, 0.9338155 , 0.9304681 , 0.92688525, 0.92326033,
       0.919514  , 0.91508305, 0.9107526 , 0.90596557, 0.90150934,
       0.89697397, 0.89218354, 0.8862491 , 0.8811144 , 0.8750308 ,
       0.86915535, 0.8627805 , 0.8557429 , 0.84842557, 0.8414775 ,
       0.83443755, 0.8271202 , 0.8191895 , 0.8125217 , 0.80480

In [ ]:
flattened_scores[0][foo[0]]

array([1.0000046 , 0.998426  , 0.9975997 , 0.99691534, 0.9963178 ,
       0.99577004, 0.9951938 , 0.99464273, 0.99406564, 0.9935037 ,
       0.99284315, 0.99224174, 0.99155235, 0.9908814 , 0.9902493 ,
       0.98964685, 0.98890775, 0.9881254 , 0.9873074 , 0.98646295,
       0.98563635, 0.9848198 , 0.9840154 , 0.98316574, 0.98230577,
       0.9812562 , 0.9801698 , 0.9791283 , 0.97809917, 0.9769713 ,
       0.9758131 , 0.97463703, 0.97324437, 0.9720334 , 0.9706463 ,
       0.96911424, 0.96758306, 0.9659832 , 0.96435106, 0.9626126 ,
       0.96078193, 0.95906293, 0.9569604 , 0.95469725, 0.9526079 ,
       0.9504701 , 0.9478901 , 0.94538134, 0.9426415 , 0.93972796,
       0.93669665, 0.9338155 , 0.9304681 , 0.92688525, 0.92326033,
       0.919514  , 0.91508305, 0.9107526 , 0.90596557, 0.90150934,
       0.89697397, 0.89218354, 0.8862491 , 0.8811144 , 0.8750308 ,
       0.86915535, 0.8627805 , 0.8557429 , 0.84842557, 0.8414775 ,
       0.83443755, 0.8271202 , 0.8191895 , 0.8125217 , 0.80480

In [ ]:
foo

array([[356978314, 232045703, 214254781, ..., 149252682, 246362214,
        137136913],
       [544132235, 576683291, 434097610, ...,  50729322, 452436606,
        164738758],
       [ 18134529, 542146987, 168616353, ..., 274704134,  23052701,
        124440409],
       ...,
       [170930692, 197004463, 357762384, ..., 351844274, 428534695,
          5448313],
       [113364127, 302575045, 289381643, ..., 549784710, 590401277,
         55335515],
       [583102731, 391643905, 325384514, ..., 290100627, 147063992,
        195185322]])

In [ ]:
foo.shape

(11, 1000)

In [ ]:
np.savez("artefacts/sampled_interaction_measures/pearson_correlation/count_1000")

In [ ]:
np.savez("artefacts/sampled_interaction_measures/pearson_correlation/count_1000", foo)

In [ ]:
dim_1 = foo[0] // d_sae

In [ ]:
dim_1

array([14525,  9441,  8718,  7609,  1555,  2248, 24067,  6076, 21572,
       18712, 23330, 10256, 10314, 15015,  8406, 18743,   978, 24361,
        1591,  5701,  4270, 20527,  7447,  8949, 20692,  2529,  9724,
        4202, 13226, 18420, 17972, 19029, 13489,  1724, 19665, 15420,
       21046, 15678, 23551,  7464, 12288,  3898, 14319,  4580,  8023,
       14440, 22626, 17819, 23623, 24491, 21745,  4051, 15506,   544,
        4734, 23716, 23969, 14599,   132, 19532, 11155, 10614, 16989,
       12105,  2282,  5904,  8104, 17174, 20413, 12309, 12984,  3707,
       18133,  3996,  4460,  7923, 24475, 24353,  6500, 13216, 21872,
       12327,  7558,  9848, 19677, 14927, 17974, 10953, 16991, 16652,
       10427, 23496,  3725,  8018,  1505, 23190,   715, 22597,  2469,
       24362, 12984, 10297, 23190,  2439,  1162, 14469, 16687,  7011,
        4248, 11045,  6040,  3078, 23224,  1737, 16408,  3317, 16092,
       21442, 20155, 12240, 16030, 22216,  1839, 13862, 13677,  6872,
        5880, 10254,

In [ ]:
foo

array([[356978314, 232045703, 214254781, ..., 149252682, 246362214,
        137136913],
       [544132235, 576683291, 434097610, ...,  50729322, 452436606,
        164738758],
       [ 18134529, 542146987, 168616353, ..., 274704134,  23052701,
        124440409],
       ...,
       [170930692, 197004463, 357762384, ..., 351844274, 428534695,
          5448313],
       [113364127, 302575045, 289381643, ..., 549784710, 590401277,
         55335515],
       [583102731, 391643905, 325384514, ..., 290100627, 147063992,
        195185322]])

In [ ]:
foo.shape

(11, 1000)

In [ ]:
np.unravel_index(foo[0][0], (d_sae, d_sae))

(14525, 11914)

In [ ]:
interaction_scores[0][14525][11914]

1.0000046